=== INIT-SGGW/HackArena2.0-MonoTanks/GameClient/Content/Localization/Language.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="Language"
           targetNamespace="http://tempuri.org/Language.xsd"
           elementFormDefault="qualified"
           xmlns="http://tempuri.org/Language.xsd"
           xmlns:mstns="http://tempuri.org/Language.xsd"
           xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:complexType name="Buttons">
		<xs:sequence>
			<xs:element name="Ok" type="xs:string"/>
			<xs:element name="JoinGame" type="xs:string"/>
			<xs:element name="Settings" type="xs:string"/>
			<xs:element name="Authors" type="xs:string"/>
			<xs:element name="Exit" type="xs:string"/>
			<xs:element name="Back" type="xs:string"/>
			<xs:element name="Leave" type="xs:string"/>
			<xs:element name="Continue" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Labels">
		<xs:sequence>
			<xs:element name="Language" type="xs:string"/>
			<xs:element name="Resolution" type="xs:string"/>
			<xs:element name="DisplayMode" type="xs:string"/>
			<xs:element name="DisplayModeWindowed" type="xs:string"/>
			<xs:element name="DisplayModeFullScreen" type="xs:string"/>
			<xs:element name="DisplayModeBorderless" type="xs:string"/>
			<xs:element name="JoinRoom" type="xs:string"/>
			<xs:element name="Nickname" type="xs:string"/>
			<xs:element name="RoomCode" type="xs:string"/>
			<xs:element name="ServerAddress" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="MessageBoxLabels">
		<xs:sequence>
			<xs:element name="ErrorOccured" type="xs:string"/>
			<xs:element name="ConnectionFailed" type="xs:string"/>
			<xs:element name="ConnectionRejected" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="ConnectionRejectedReason">
		<xs:sequence>
			<xs:element name="InvalidJoinCode" type="xs:string"/>
			<xs:element name="MissingNickname" type="xs:string"/>
			<xs:element name="NicknameExists" type="xs:string"/>
			<xs:element name="InvalidUrlPath" type="xs:string"/>
			<xs:element name="GameFull" type="xs:string"/>
			<xs:element name="TooManyFailedAttempts" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="Other">
		<xs:sequence>
			<xs:element name="Loading" type="xs:string"/>
			<xs:element name="Waiting" type="xs:string"/>
			<xs:element name="Connecting" type="xs:string"/>
			<xs:element name="NoDetails" type="xs:string"/>
			<xs:element name="ServerNotResponding" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>

	<xs:element name="Content">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="Buttons" type="mstns:Buttons"/>
				<xs:element name="Labels" type="mstns:Labels"/>
				<xs:element name="MessageBoxLabels" type="mstns:MessageBoxLabels"/>
				<xs:element name="ConnectionRejectedReason" type="mstns:ConnectionRejectedReason"/>
				<xs:element name="Other" type="mstns:Other"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== INIT-SGGW/HackArena2.0-MonoTanks/GameClient/Content/Localization/French.xml
<?xml version="1.0" encoding="utf-8"?>
<Content xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://tempuri.org/Language.xsd"
         xsi:schemaLocation="http://tempuri.org/Language.xsd Language.xsd">

	<Buttons>
		<JoinGame>Rejoindre</JoinGame>
		<Settings>Paramètres</Settings>
		<Authors>Auteurs</Authors>
		<Exit>Quitter</Exit>
		<Back>Retour</Back>
	</Buttons>

	<Labels>
		<Language>Langue</Language>
		<Resolution>Résolution</Resolution>
		<DisplayMode>Mode d'affichage</DisplayMode>
		<DisplayModeWindowed>Fenêtré</DisplayModeWindowed>
		<DisplayModeFullScreen>Plein écran</DisplayModeFullScreen>
		<DisplayModeBorderless>Sans bordure</DisplayModeBorderless>
	</Labels>

	<Other>
	</Other>

</Content>

=== INIT-SGGW/HackArena2.0-MonoTanks/GameClient/Content/Localization/English.xml
<?xml version="1.0" encoding="utf-8"?>
<Content xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://tempuri.org/Language.xsd"
         xsi:schemaLocation="http://tempuri.org/Language.xsd Language.xsd">

	<Buttons>
		<JoinGame>Join</JoinGame>
		<Settings>Settings</Settings>
		<Authors>Authors</Authors>
		<Exit>Exit</Exit>
		<Back>Back</Back>
	</Buttons>

	<Labels>
		<Language>Language</Language>
		<Resolution>Resolution</Resolution>
		<DisplayMode>Screen type</DisplayMode>
		<DisplayModeWindowed>Windowed</DisplayModeWindowed>
		<DisplayModeFullScreen>Fullscreen</DisplayModeFullScreen>
		<DisplayModeBorderless>Borderless</DisplayModeBorderless>
	</Labels>

	<Other>
	</Other>

</Content>
